import React from 'react';
import { motion } from 'framer-motion';

const Tag = ({ children, color="slate", size="md" }) => {
  const p = size==="xs" ? "2px 8px" : size==="sm" ? "4px 10px" : "6px 14px";
  const f = size==="xs" ? 11 : size==="sm" ? 12 : 13;
  return (
    <span style={{ display:"inline-flex", padding:p, fontSize:f, fontWeight:700, borderRadius:20, letterSpacing:"0.04em", textTransform:"uppercase",
      background:`var(--${color}-light)`, color:`var(--${color}-dark)`, border:`1px solid rgba(13,148,136,0.15)` }}>
      {children}
    </span>
  );
};

const BlogShell = ({ children, onNav }) => (
  <motion.div initial={{ opacity:0,y:18 }} animate={{ opacity:1,y:0 }} transition={{ duration:0.35 }} style={{ minHeight:"100vh", paddingTop:88, paddingBottom:80, background:"var(--slate-50)" }}>
    <div style={{ maxWidth:800, margin:"0 auto", padding:"0 20px" }}>
      <button onClick={()=>onNav("blog")} style={{ display:"inline-flex", alignItems:"center", gap:6, background:"none", border:"none", cursor:"pointer", fontSize:13, color:"var(--slate-500)", fontFamily:"'DM Sans',sans-serif", marginBottom:24, padding:0 }}>
        Back to Blog
      </button>
      {children}
    </div>
  </motion.div>
);

export const BlogSystemDesign = ({ onNav }) => (
  <BlogShell onNav={onNav}>
    <Tag color="teal">System Design</Tag>
    <h1 className="brig" style={{ fontSize:"clamp(24px,4vw,38px)", fontWeight:800, color:"var(--slate)", letterSpacing:"-0.03em", lineHeight:1.15, marginTop:16, marginBottom:8 }}>How to Ace System Design Interviews in 2026</h1>
    <p style={{ fontSize:14, color:"var(--slate-400)", marginBottom:32 }}>August 2026 ┬╖ 12 min read</p>
    <div style={{ display:"flex", flexDirection:"column", gap:24, fontSize:15.5, color:"var(--slate-700)", lineHeight:1.8 }}>
      <p>System design interviews are the most feared round at FAANG and top-tier tech companies. Unlike algorithm questions, there is no single correct answer. The interviewer is evaluating how you think, how you communicate, and whether you can reason about trade-offs under ambiguity. This guide gives you a repeatable, proven framework to perform confidently in any system design interview in 2026 and beyond. A system design interview is fundamentally about managing complexity and scale. We will break down exactly how you should structure your 45-minute session to maximize your signal-to-noise ratio and demonstrate senior-level engineering maturity.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 1: Clarify Requirements Before You Draw Anything</h2>
      <p>The most common mistake candidates make is jumping straight into the design. Spend the first 5 minutes asking clarifying questions. Establish functional requirements (what must the system do?), non-functional requirements (scale, latency, reliability), and constraints (read-heavy vs. write-heavy? Global vs. regional?). A system designed for 10,000 daily active users is architecturally different from one serving 100 million. Always establish scale before designing solutions. Ask the interviewer specific questions: "Are we designing this for North America or a global audience?" or "What is our expected read-to-write ratio?" These questions prove you think before you build.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 2: Back-of-the-Envelope Scale Estimation</h2>
      <p>Reason about scale numerically. If you have 100 million users and 10% are daily active, each uploading 2 photos per day, that is 20 million uploads per day or roughly 230 uploads per second. At 500KB per photo, you need approximately 10TB of new storage daily. These calculations drive technology choices and reveal bottlenecks before you draw a single box. Interviewers specifically look for structured quantitative reasoning here. Do not skip this step, and do not get bogged down in extreme precision. Use round numbers. 1 day is approximately 100,000 seconds. Keep your math simple, verbalize it, and write it on the whiteboard.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 3: High-Level Architecture First, Then Scale It</h2>
      <p>Start with the simplest architecture that satisfies core requirements: Client to Load Balancer to Application Servers to Database. Explain each component's role clearly. Then identify where this architecture breaks at your target scale and systematically layer in solutions: caching with Redis or Memcached for hot reads, a CDN for static assets, message queues like Kafka or SQS for async processing, and read replicas or database sharding for write throughput. This progressive enhancement shows that you understand you don't build a distributed system from day one unless the scale demands it. Start simple, identify the bottleneck, and resolve it.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 4: Choose and Justify Your Database</h2>
      <p>Use a relational database such as PostgreSQL or MySQL for structured data, complex queries, and ACID compliance. Choose NoSQL databases like DynamoDB, Cassandra, or MongoDB for horizontal scalability, schema flexibility, or high write throughput. Use Cassandra specifically for time-series or event-log workloads like activity feeds or IoT telemetry. Never just name a technology without explaining the trade-offs you evaluated and why it fits your specific requirements better than the alternatives. Data modeling is critical; draw out your tables, partitions, and sort keys. The database choice is often the single most important decision in the entire interview.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 5: Apply the CAP Theorem Fluently</h2>
      <p>Distributed systems can guarantee at most two of three properties: Consistency (all nodes see the same data simultaneously), Availability (every request receives a response), and Partition Tolerance (the system continues despite network partitions). Since partitions are inevitable in distributed systems, you are effectively choosing between CP systems for banking and payments, and AP systems for social feeds and analytics. Being able to articulate this trade-off fluently is a strong signal of senior-level thinking. Talk about eventual consistency models versus strong consistency requirements.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 6: Robust Caching Strategy</h2>
      <p>Introduce a Redis or Memcached layer in front of your database for hot-path reads. Discuss cache-aside, write-through, or write-behind patterns, LRU eviction policies, TTL-based expiration, and event-driven invalidation. Show you have considered cache stampede, which is the scenario where simultaneous cache expiry causes a thundering herd on your database. Demonstrating awareness of failure modes strongly differentiates your performance from average candidates. Always discuss caching on multiple levels: client-side, CDN, API gateway, and database layers.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 7: Deep Dive and Failure Modes</h2>
      <p>Reserve the final 10 to 15 minutes for a deep dive on the highest-risk component of your design. Walk through concrete failure scenarios: what happens when the cache layer is unavailable? When the primary database goes down? How does the system degrade gracefully when downstream services fail? Discussing circuit breakers, retries with exponential backoff, and graceful degradation distinguishes senior-level candidates from those who can only design the happy path. In the real world, servers burn down, networks partition, and disks fail. Your design must account for chaos.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 8: Communicate Like a Senior Engineer</h2>
      <p>Many candidates fail system design interviews not because their architecture is incorrect, but because their communication is disorganized. Narrate your design in clear layers: requirements, estimates, high-level architecture, data model, bottlenecks, scale strategy, and reliability plan. Signpost every transition so the interviewer can follow your reasoning. Phrases like "Now that we've scoped read traffic, let's discuss caching" or "Next I want to show failure recovery for the write path" create structure and trust. Interviewers are evaluating whether they can collaborate with you in design reviews, not just whether you can memorize diagrams.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Step 9: 30-Day Practice Plan</h2>
      <p>A practical prep plan beats random practice. Week 1: revise fundamentals—load balancing, partitioning, CAP, consistency, caching, and messaging. Week 2: solve one common prompt daily, such as URL shortener, chat app, file storage, and news feed. Week 3: time-box full mock interviews and focus on whiteboard clarity. Week 4: run simulated stress rounds where a friend or AI pushes edge cases aggressively. After every session, write a post-mortem: what bottleneck you missed, which assumptions were weak, and how your explanation can be cleaner next time. Improvement compounds quickly when you review deliberately.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Final Interview Day Checklist</h2>
      <p>Before the interview, keep a short checklist in mind: clarify requirements, estimate scale, start with a simple design, identify bottlenecks, justify trade-offs, discuss reliability, and summarize next steps. If you get stuck, reset and communicate your assumptions rather than going silent. It's acceptable to revise your design when the interviewer introduces new constraints; in fact, this adaptability is a positive signal. The best candidates stay calm, think in systems, and communicate with confidence. Master this process and system design turns from the scariest round into your biggest advantage.</p>
    </div>
  </BlogShell>
);

export const BlogSTAR = ({ onNav }) => (
  <BlogShell onNav={onNav}>
    <Tag color="teal">Behavioral</Tag>
    <h1 className="brig" style={{ fontSize:"clamp(24px,4vw,38px)", fontWeight:800, color:"var(--slate)", letterSpacing:"-0.03em", lineHeight:1.15, marginTop:16, marginBottom:8 }}>Mastering the STAR Method for Behavioral Interviews</h1>
    <p style={{ fontSize:14, color:"var(--slate-400)", marginBottom:32 }}>August 2026 ┬╖ 10 min read</p>
    <div style={{ display:"flex", flexDirection:"column", gap:24, fontSize:15.5, color:"var(--slate-700)", lineHeight:1.8 }}>
      <p>Behavioral interviews account for at least 50% of your total interview score at most top tech companies, yet most candidates massively underprepare for them. The STAR method, standing for Situation, Task, Action, Result, is the proven framework for structuring compelling behavioral answers that stick. This guide teaches you exactly how to use it, how to avoid the most common pitfalls, and how to adapt it for different question types.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>The Four Components of STAR</h2>
      <p>Situation: Set the scene in 2 to 3 sentences maximum, covering who was involved, what project, and what was at stake. Candidates consistently spend too long here. Task: Describe your specific responsibility and the problem that fell to you personally. Action: The most critical component. Describe specifically what you did, not what your team did. Use I, not we. Detail the steps, decisions, and your explicit reasoning. Result: Quantify the impact. Saying we shipped faster is weak. Saying we reduced deployment time by 40%, enabling 3 additional feature releases per quarter, is strong.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Worked Example: Leadership Under Pressure</h2>
      <p>Question: Tell me about a time you led a project under significant time pressure.</p>
      <p>Situation: A critical payment integration was 6 weeks from its regulatory compliance deadline and our senior engineer had just left the company unexpectedly.</p>
      <p>Task: I was asked to step up as technical lead to deliver the project on time with a team of two junior engineers who were unfamiliar with the codebase.</p>
      <p>Action: I audited the existing codebase and created a realistic project plan. I identified that 3 of the 5 planned features could be deprioritized to meet the regulatory minimum. I ran daily 15-minute standups, paired with junior engineers on the most complex components, built an automated test suite to catch regressions early, and established a direct channel with the compliance team to surface blockers immediately.</p>
      <p>Result: We delivered the compliance features one week ahead of deadline. The project received zero violations in the regulatory audit. The automated test suite reduced QA time by 60% for all subsequent payment features. One of the junior engineers I mentored was promoted 6 months later.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>The 5 Most Common STAR Mistakes</h2>
      <p>First, using we instead of I. Interviewers are evaluating your personal contribution specifically. Second, spending too long on Situation. Keep Situation and Task combined under 20% of your total answer time. Third, omitting the Result entirely. Always end with a specific, measurable outcome because this is the most commonly skipped component. Fourth, fabricating stories. Experienced interviewers probe deeply with follow-up questions and vague details under pressure instantly destroy credibility. Fifth, using the same story for every question. Prepare 8 to 10 distinct stories spanning leadership, conflict, failure, ambiguity, collaboration, innovation, and time pressure scenarios.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>How to Build a Strong STAR Story Bank</h2>
      <p>Create a story bank spreadsheet with columns for question type, company value being tested, the specific challenge, your actions, measurable results, and lessons learned. Build stories across leadership, stakeholder conflict, technical failure, ambiguity, ownership, and collaboration. For each story, prepare a 90-second version and a 3-minute extended version. This gives you flexibility depending on the interviewer's pace and follow-up depth. Rehearse stories out loud until they feel natural, not memorized. The goal is clarity and authenticity, not robotic delivery.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Adapting STAR for Different Companies</h2>
      <p>Different companies emphasize different signals. At Amazon, tie your answers to specific Leadership Principles and be ready for deep probes on ownership and decision quality. At Google, show humility, learning velocity, and collaboration under ambiguity. At Meta, highlight speed, bold experimentation, and measurable product impact. At Microsoft, emphasize cross-team partnership and customer empathy. The underlying STAR structure stays the same, but your framing should map to what that company values most. Candidates who tailor stories to company expectations consistently outperform equally qualified peers who use generic responses.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>How to Handle Follow-up Questions</h2>
      <p>Strong interviewers test depth with follow-ups: Why did you choose that approach? What trade-offs did you evaluate? What would you do differently now? Prepare by documenting decision alternatives in every major story. If you made a mistake, own it and explain what changed in your process afterward. That demonstrates maturity. Avoid defensive answers or vague generalizations under pressure. Precision builds credibility. A concise "I chose option A due to timeline risk, but in hindsight option B would have reduced maintenance cost" is often more impressive than pretending every decision was perfect.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Last 7 Days Before the Interview</h2>
      <p>In your final week, run daily mock behavioral rounds. Record yourself answering five common prompts and review for clarity, filler words, and timing. Make sure each answer has a clear Result with a metric, customer impact, or operational improvement. Practice transitions like "The key action I took was..." and "The measurable outcome was..." so your structure remains obvious even under stress. On interview day, slow down, smile, and treat the conversation as collaborative problem-solving. STAR works best when your answers sound human, specific, and evidence-based.</p>
    </div>
  </BlogShell>
);

export const BlogBehavioral = ({ onNav }) => (
  <BlogShell onNav={onNav}>
    <Tag color="teal">FAANG Prep</Tag>
    <h1 className="brig" style={{ fontSize:"clamp(24px,4vw,38px)", fontWeight:800, color:"var(--slate)", letterSpacing:"-0.03em", lineHeight:1.15, marginTop:16, marginBottom:8 }}>The Complete Guide to Behavioral Interviews at Top Tech Companies</h1>
    <p style={{ fontSize:14, color:"var(--slate-400)", marginBottom:32 }}>August 2026 ┬╖ 14 min read</p>
    <div style={{ display:"flex", flexDirection:"column", gap:24, fontSize:15.5, color:"var(--slate-700)", lineHeight:1.8 }}>
      <p>Every major tech company including Google, Amazon, Meta, Microsoft, and Apple uses behavioral interviews to assess whether candidates embody their core cultural values and leadership principles. The specific questions vary by company, but the underlying competencies being evaluated are remarkably consistent. Understanding what interviewers are actually measuring, and why, is the fastest way to improve your performance significantly.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Amazon: Leadership Principles</h2>
      <p>Amazon is the most rigorous behavioral interviewer in the industry. Every question maps explicitly to one of Amazon's 16 Leadership Principles including Customer Obsession, Ownership, Invent and Simplify, Earn Trust, and Deliver Results. Your interviewer will probe each answer deeply with follow-up questions such as what would you have done differently and how did your team react. You should prepare at least 2 distinct stories per Leadership Principle, meaning 32 or more prepared stories minimum. Amazon specifically penalizes reusing the same story across different Leadership Principles.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Google: Googleyness and Intellectual Humility</h2>
      <p>Google evaluates behavioral fit through Googleyness, which encompasses intellectual humility, genuine collaboration, ambiguity tolerance, and comfort with uncertainty. Google interviewers are less rigid about specific frameworks than Amazon but probe deeply for evidence of initiative, cross-functional influence, and the ability to disagree and commit. Strong Google behavioral answers demonstrate that you changed your mind based on data, unified stakeholders with conflicting interests, and delivered results despite unclear or shifting requirements.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Meta: Move Fast, Be Bold, Focus on Impact</h2>
      <p>Meta's behavioral interviews center on Move Fast, Be Bold, and Focus on Impact. They want to hear about launching quickly despite incomplete information, taking calculated risks that paid off, and driving measurable business impact at scale. Meta interviewers specifically penalize over-engineering and excessive caution when shipping. Stories demonstrating speed, comfort with ambiguity, and rapid iteration are crucial.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Microsoft: Growth Mindset and Collaboration</h2>
      <p>Microsoft places heavy emphasis on growth mindset, inclusivity, and collaborative execution across teams. Interviewers look for examples where you sought feedback, revised your approach, and improved outcomes without ego. They also evaluate how you handle disagreements in cross-functional settings, especially when partnering with product, design, security, and operations teams. Strong stories often include conflict resolution, stakeholder alignment, and customer empathy. Demonstrating technical skill is essential, but showing that you elevate the team around you is what drives exceptional performance in Microsoft-style behavioral loops.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Core Competencies Behind Most Behavioral Questions</h2>
      <p>Across companies, interviewers repeatedly test a shared set of competencies: ownership, prioritization, communication clarity, resilience, data-driven decision making, influence without authority, and learning from failure. If you map your story bank to these dimensions, you can handle almost any prompt. For example, "Tell me about a failure" tests accountability and reflection. "Tell me about conflict" tests emotional intelligence and collaboration. "Tell me about impact" tests business orientation. Understanding the underlying competency makes it easier to adapt examples in real time instead of memorizing rigid scripts.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>How to Prepare Better Than 90% of Candidates</h2>
      <p>Most candidates prepare behavioral interviews passively by reading question lists. High performers prepare actively. Start by writing 10 to 12 high-quality stories using STAR. Then conduct timed mock rounds with peers or AI interview tools that interrupt, challenge assumptions, and ask multi-layered follow-ups. After each mock, score yourself on specificity, quantification, and composure. Replace vague statements with concrete details: exact timeline pressure, team size, technical constraints, and measurable outcomes. Within two weeks, this deliberate practice dramatically improves both confidence and consistency.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>Interview-Day Execution Framework</h2>
      <p>During the interview, take a brief pause before answering so you can select the strongest story for that question. State the situation concisely, focus most of your time on your actions, and finish with a quantifiable result. If you receive follow-ups, treat them as opportunities to show depth rather than signs that your first answer failed. Keep your tone calm, direct, and reflective. Great behavioral interviews feel like thoughtful leadership conversations. When you combine structured stories with measured delivery, you become memorable for the right reasons.</p>
    </div>
  </BlogShell>
);

export const BlogResume = ({ onNav }) => (
  <BlogShell onNav={onNav}>
    <Tag color="teal">Resume</Tag>
    <h1 className="brig" style={{ fontSize:"clamp(24px,4vw,38px)", fontWeight:800, color:"var(--slate)", letterSpacing:"-0.03em", lineHeight:1.15, marginTop:16, marginBottom:8 }}>Resume Tips for Software Engineers: How to Get Past the ATS</h1>
    <p style={{ fontSize:14, color:"var(--slate-400)", marginBottom:32 }}>August 2026 ┬╖ 9 min read</p>
    <div style={{ display:"flex", flexDirection:"column", gap:24, fontSize:15.5, color:"var(--slate-700)", lineHeight:1.8 }}>
      <p>Your software engineering resume has exactly one job: getting you the interview. It is not an autobiography, nor is it a comprehensive list of every technology you have ever touched. Recruiters and engineering managers spend an average of 6 seconds scanning a resume before making a decision. To survive the Applicant Tracking System (ATS) and impress a human reader, your resume must be impeccably formatted, highly scannable, and relentlessly focused on quantifiable impact.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>1. Standardize Your Formatting</h2>
      <p>The biggest mistake engineers make is using overly designed, multi-column resume templates with progress bars for skills. These completely break most ATS parsers. Use a clean, single-column layout with standard fonts like Arial, Helvetica, or Garamond. Use standard headings: Education, Experience, Projects, and Skills. Submit your resume strictly as a PDF unless explicitly requested otherwise. An ATS must be able to cleanly highlight text from your document.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>2. The XYZ Formula for Bullet Points</h2>
      <p>Google's recruiters popularized the XYZ formula, and it remains the gold standard for engineering resumes: Accomplished [X] as measured by [Y], by doing [Z]. Stop writing "Worked on backend APIs." Instead, write: "Reduced API response latency by 40% (X) resulting in a 15% increase in user retention (Y) by implementing Redis caching and optimizing PostgreSQL queries (Z)." Every bullet point under your experience should start with a strong action verb and end with a quantifiable metric.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>3. Keyword Optimization and Tailoring</h2>
      <p>An ATS parses your resume for specific keywords matching the job description. If a job requires "React, Node.js, and AWS," ensure those exact terms appear prominently in your Skills section and are contextualized in your Experience bullet points. Do not keyword stuff (e.g., listing 50 programming languages in a block), but do tailor your core skills to match the job description closely. If you have a matching skill, feature it prominently.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>4. Build a Strong Project Section</h2>
      <p>For freshers and early-career engineers, projects often carry as much weight as internships. Include 2 to 4 relevant projects with concise bullet points describing the problem solved, technologies used, and measurable impact. Even academic or side projects can be compelling if you demonstrate thoughtful engineering decisions and outcomes. Mention scale where possible: number of users, request volume, latency improvements, model accuracy, or deployment reliability. Avoid generic descriptions such as "Built a web app." Instead, explain what made your implementation technically meaningful.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>5. Prioritize Impact Over Task Lists</h2>
      <p>A weak resume reads like a job description. A strong resume reads like a record of outcomes. Replace responsibility-based bullets ("Responsible for backend APIs") with impact-based bullets ("Reduced p95 latency by 38% by introducing query caching and connection pooling"). Show business or user impact whenever possible: conversion uplift, downtime reduction, support ticket decline, faster release cycles, or cost savings. Recruiters are trying to predict your future value from limited evidence. Quantified impact is the fastest way to make that evidence credible.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>6. Common Resume Rejections and How to Avoid Them</h2>
      <p>Many otherwise qualified resumes get rejected for preventable reasons: inconsistent formatting, grammatical errors, walls of text, irrelevant coursework overload, and missing links to GitHub or portfolio projects. Another frequent issue is listing advanced technologies without proof of depth in projects or experience. If you claim Kubernetes, show where and how you used it. If you claim distributed systems, show a project that actually involved queueing, retries, or scaling bottlenecks. Consistency between claimed skills and demonstrated work is critical for trust.</p>
      <h2 className="brig" style={{ fontSize:22, fontWeight:700, color:"var(--slate)" }}>7. Final Resume Review Checklist</h2>
      <p>Before applying, run a final checklist: one page for freshers, clear section hierarchy, measurable bullets, targeted keywords, active verbs, and zero spelling errors. Verify every link, ensure PDF export quality, and test text selection to confirm ATS readability. Ask one technical mentor and one non-technical friend to review it—the first checks technical credibility while the second checks clarity. Tailor your resume for each role cluster (backend, frontend, data, mobile) instead of sending a single generic version everywhere. A precise resume dramatically increases interview callbacks.</p>
    </div>
  </BlogShell>
);
